### ISSUE TITLE
Extend handshake to support photon key exchange

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/spark-protocol#5]

**Comment by mbullington** [comment]
Hello, besides this, what's the status on Photon support in the spark-protocol package? Just curious, I'm using Photon and would like to also use spark-protocol. Thank you.

**Comment by joltup** [comment]
+1

**Comment by tslater** [comment]
Yeah so far I'm getting stuck here. I'm excited to see this fixed. I'd like to contribute but worry this is over my head.

**Comment by dmiddlecamp** [comment]
I've posted a PR here that I think should allow photons to connect, I want to do more to make it easier for photons (so their self-reported keys can just be used naturally), but I wanted to get this fix out as soon as possible first.

https://github.com/spark/spark-protocol/pull/8

**Comment by ysangkok** [comment]
Is this still an issue?

**Comment by dmiddlecamp** [comment]
Hi @ysangkok ,

  Good question!  I merged my PR a few months back, and released a new npm module with the changes.  When I tested the changes, they worked great for me, so I think the issue is fixed.  You might need to run an `npm update`, or reinstall the module to get the update though.

If it is fixed, I'll go ahead and close this issue then.  :) 

Thanks!
David
