### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by mbullington** [spark/spark-protocol#7]
Hello!

I'm very eager to try out spark-protocol in a project that I'm working on, but I've found the following problem. In your LICENSE, you state the license for the project is LGPLv3. However, the header on individual files says the license is GPLv3. Here is the header in question.

```
/*
*   Copyright (C) 2013-2014 Spark Labs, Inc. All rights reserved. -  https://www.spark.io/
*
*   This file is part of the Spark-protocol module
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License version 3
*   as published by the Free Software Foundation.
*
*   Spark-protocol is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with Spark-protocol.  If not, see <http://www.gnu.org/licenses/>.
*
*   You can download the source here: https://github.com/spark/spark-protocol
*/
```

Is this project dual licensed, or is it licensed under LGPLv3 or GPLv3? Thank you.

**Comment by zsup** [comment]
Sorry, that looks like a mistake on our part; this should be LGPL, not GPL. @emilyrose do you think you could fix this when you have a sec?

**Comment by dmiddlecamp** [comment]
oh that's very strange!

**Comment by emilyrose** [comment]
hey @mbullington, thanks for the report!

I've fixed the license to show LGPLv3 as intended! Great catch.

cc: @zsup @dmiddlecamp :smile_cat: 

commit here: 562b7bb4492fc53714fd634bbf8d2c0153aeb919

**Comment by dmiddlecamp** [comment]
@emilyrose -- I think the intention is updating the individual file license headers as well?  I'm not sure we meant to change the root license from LGPL

**Comment by emilyrose** [comment]
@dmiddlecamp ah hah! I didn't realize we had license headers as well. I'll swap those out.

**Comment by emilyrose** [comment]
Alright, and with 397d3aacda4ef7f762048f529b305909ee7d8614 I believe we are good to go!
Let me know if anyone notices something I missed.

**Comment by emilyrose** [comment]
also, thanks for the heads up, @dmiddlecamp!
